#!/usr/bin/bash
if [ $# = 0 ]; then
    echo "missing arguments!"
    echo "Command at least needs a problem name"
    exit 1
fi
s="main.py -c -d ../exercises/ -n $1"
if [ $# -gt 1 ]; then
    s=$s" -t ${@:2:99}"
fi

echo "> python3 $s"
python3 $s